version: '3.8'

services:
  nginx:
    image: nginx:1.23.1-alpine
    ports:
      - ${EXPOSE_HTTP_PORT}:80
    volumes:
      - ../code:/code
      - ./image/nginx/config/site.conf:/etc/nginx/conf.d/site.conf
    depends_on:
      - php

  php:
    image: php:8.1.0-fpm
    volumes:
      - ../public:/code

networks:
  default:
    driver: bridge

#  php-consumer:
#    container_name: ${CONTAINER_PREFIX}_php_consumer
#    profiles: ["dev", "prod", "local"]
#    build:
#      context: image/php-consumer
#      args:
#        - UID
#    volumes:
#      - ../:/var/www:delegated
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
#    env_file:
#      - ./.env
#    networks:
#      - default

#  nginx:
#    container_name: ${CONTAINER_PREFIX}_nginx
#    profiles: ["dev", "prod", "local"]
#    build:
#      context: image/nginx
#      args:
#        - CONTAINER_PREFIX
#    volumes:
#      - ../public:/var/www/public:delegated
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
#    depends_on:
#      - php
#    networks:
#      - default
#    ports:
#      - ${EXPOSE_HTTP_PORT}:80
